package tests

import (
	"testing"

	"github.com/google/uuid"
	"github.com/stretchr/testify/require"
)

func TestIntegerPrimaryKeyAutoRowID(t *testing.T) {
	db := openDB(t)
	assertExec(t, db, "CREATE TABLE foo (id INTEGER PRIMARY KEY, value TEXT)")
	assertExec(t, db, "INSERT INTO foo (value) VALUES ('first')")
	assertExec(t, db, "INSERT INTO foo (value) VALUES ('second')")
	assertQueryRows(t, db, "SELECT id, value FROM foo", [][]any{
		{int64(1), "first"},
		{int64(2), "second"},
	})
}

func TestIntegerPrimaryKeyExplicitValue(t *testing.T) {
	db := openDB(t)
	assertExec(t, db, "CREATE TABLE foo (id INTEGER PRIMARY KEY, value TEXT)")
	assertExec(t, db, "INSERT INTO foo (id, value) VALUES (5, 'x')")
	assertExec(t, db, "INSERT INTO foo (id, value) VALUES (7, 'z')")
	assertQueryRows(t, db, "SELECT id, value FROM foo", [][]any{
		{int64(5), "x"},
		{int64(7), "z"},
	})
}

func TestUuidPrimaryKeyAutoGenerated(t *testing.T) {
	db := openDB(t)
	assertExec(t, db, "CREATE TABLE foo (id UUID PRIMARY KEY, value TEXT)")
	assertExec(t, db, "INSERT INTO foo (value) VALUES ('first')")
	assertExec(t, db, "INSERT INTO foo (value) VALUES ('second')")

	sqlRows, err := db.Query("SELECT id, value FROM foo")
	require.NoError(t, err)
	rows := scanRows(t, sqlRows)
	require.Len(t, rows, 2)

	seen := map[string]bool{}

	for _, row := range rows {
		id, ok := row[0].(string)
		require.True(t, ok, "id should be a uuid string, got %T", row[0])
		_, err := uuid.Parse(id)
		require.NoError(t, err)
		require.False(t, seen[id], "generated uuids must be unique")
		seen[id] = true
	}
}

func TestSelectRowId(t *testing.T) {
	db := openDB(t)
	assertExec(t, db, "CREATE TABLE foo (id TEXT, value REAL)")
	assertExec(t, db, "INSERT INTO foo VALUES ('a', 1)")
	assertExec(t, db, "INSERT INTO foo VALUES ('b', 2)")
	assertQueryRows(t, db, "SELECT ROWID(), id FROM foo", [][]any{
		{int64(1), "a"},
		{int64(2), "b"},
	})
}

func TestSelectRowIdInWhere(t *testing.T) {
	db := openDB(t)
	assertExec(t, db, "CREATE TABLE foo (id TEXT, value REAL)")
	assertExec(t, db, "INSERT INTO foo VALUES ('a', 1)")
	assertExec(t, db, "INSERT INTO foo VALUES ('b', 2)")
	assertQueryValue(t, db, "SELECT value FROM foo WHERE ROWID() = 2", float64(2))
}

func TestPrimaryKeyAutoValuePersists(t *testing.T) {
	db, fp := openFileDB(t)
	assertExec(t, db, "CREATE TABLE foo (id INTEGER PRIMARY KEY, value TEXT)")
	assertExec(t, db, "INSERT INTO foo (value) VALUES ('first')")
	require.NoError(t, db.Close())

	reopened := reopenFileDB(t, fp)
	assertQueryRow(t, reopened, "SELECT id, value FROM foo", []any{int64(1), "first"})
	assertExec(t, reopened, "INSERT INTO foo (value) VALUES ('second')")
	assertQueryRows(t, reopened, "SELECT id, value FROM foo", [][]any{
		{int64(1), "first"},
		{int64(2), "second"},
	})
}
